### ISSUE TITLE
Failed to execute script rmexplorer_pyi

### ISSUE THREAD

**Issue by nasendackel** [bruot/pyrmexplorer#10]
Hi, I just upgraded my remarkable to version 2.1.1.3. 

Since that I get this error, when I want to launch rmExplorer:

Failed to execute script rmexplorer_pyi

Please help!

Thanks Christoph

Sadly there is no real alternative to rmExplorer. It is still the best tool. Thanks!!!!

**Comment by nasendackel** [comment]
Can't be even just be a problem with windows. I will try to rebuild everything...

**Comment by bruot** [comment]
Hi. Sorry for the late reply. I think you are confusing what files to launch. You are not supposed to launch rmexplorer_pyi.py. This is a script that is used only for compilation of the Windows executable, and still, it should not be executed directly even if you want to compile rMExplorer.

If you want to just launch rmExplorer, it is as usual, as explained in the Wiki (and the methods shown there do not require the rmexplorer_pyi.py file at all).

If you want to compile, use the .bat file.

Let me know if you manage to fix your problem.

**Comment by nasendackel** [comment]
Hi, maybe I expressed myself in a wrong way. I change nothing. I can't excute your release or compile with the bat.

When I start the rmexplorer.exe I get:
Failed to execute script rmexplorer_pyi

**Comment by bruot** [comment]
It can happen if you have missing files in the folder that contains rmexplorer.exe. Can you try by downloading again the latest release?

https://github.com/bruot/pyrmexplorer/releases/download/v1.3.1/rmexplorer_1.3.1_win_x64.zip

**Comment by nasendackel** [comment]
Yes. I still get the same mistake on two different windows machines.

**Comment by nasendackel** [comment]
Strange. But now it works fine again. Maybe there was a windows bug or something. 
Works! So sorry for the trouble!
