### ISSUE TITLE
why not simply use sshmount

### ISSUE THREAD

**Issue by pannous** [bruot/pyrmexplorer#2]
```
sudo apt-get install sshfs  
sudo sshfs -o allow_other,defer_permissions root@xxx.xxx.xxx.xxx:/ /mnt/remarkable
```

**Comment by bruot** [comment]
On the filesystem of the tablet, the files structure is [not in a human-readable hierarchy](https://remarkablewiki.com/tech/filesystem). Also the documents themselves are stored in a special format - see details in same link. This makes using SSH pretty useless, except for backups (feature recently added to master branch).

With rMExplorer, files can be browsed and downloaded as PDF or PNG. Using the USB web interface allows letting the tablet take care of the conversion to PDF, which gives very good rendering.

**Comment by pannous** [comment]
oh ok, thanks
