### ISSUE TITLE
Upload files to folders

### ISSUE THREAD

**Issue by tdussa** [bruot/pyrmexplorer#22]
When entering a folder on the rM, rMExplorer shows the folder's contents.  However, when then a file is uploaded, it is uploaded to the root folder.  This is counterintuitive; the file should be uploaded to the currently opened folder instead.

**Comment by bruot** [comment]
I agree this would make more sense. But AFAIK, the USB API used for the uploads does not allow choosing the directory.

**Comment by tdussa** [comment]
ACK.  If the API cannot do that, then that sucks, but nothing you can do about it.  THX for the reply!
