### ISSUE TITLE
Found Trojan in reMarkable.com

### ISSUE THREAD

**Issue by nasendackel** [bruot/pyrmexplorer#4]
Hi, Windows defender found a Trojan:Win32/Fuerboss.E!cl in the windows executable. In the .exe file, not .com (sorry for the wrong title)

**Comment by bruot** [comment]
Thanks for the report. Looks like a false positive. I have tested the .zip and .exe of both 32 and 64 bits versions and the vast majority of antiviruses found no threats. It has been reported many times that pyinstaller (used to compile the rMExplorer code) often makes antiviruses complain - just google "pyinstaller trojan".

If you feel uncomfortable running the .exe, you can still use rMExplorer with Python (method 2 in the [install notes](https://github.com/bruot/pyrmexplorer/wiki)).
