### ISSUE TITLE
Download all creates error

### ISSUE THREAD

**Issue by nasendackel** [bruot/pyrmexplorer#5]
Hi there!

On Windows 10 running python 3.7 version 1.20 suddenly creates this error: Download single files works fine

rmexplorerwindow.py", line 549, in downloadAll
    self.downloadDir('', '')
AttributeError: 'RmExplorerWindow' object has no attribute 'downloadDir'

**Comment by bruot** [comment]
Oh, you're right! I will fix that soon. In the meantime, you can always select all the folders and right click to download them at once.

**Comment by bruot** [comment]
Fixed by 77385a7e9082198c071e38f512daf6ba70cd08d8.
