### ISSUE TITLE
Export PDF as grayscale

### ISSUE THREAD

**Issue by nasendackel** [bruot/pyrmexplorer#8]
Hi is there a way to export PDF as grayscale. Because of the display of the remarkable I am really uses to use no colors. The Marker also shocks me, when it is exported.

**Comment by bruot** [comment]
Hello. Editing the PDF may be a bit tricky, but converting the PNG exports to grayscale is fine.

However I think that having the grayscale feature would only be useful to very few people, so I am not sure it is relevant to complicate the Export window with such a new option.

I am closing this issue, but if others are interested, they can manifest themselves.
